apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wasmcloud-secrets
  name: wasmcloud-secrets
spec:
  selector:
    matchLabels:
      app: wasmcloud-secrets
  template:
    metadata:
      labels:
        app: wasmcloud-secrets
    spec:
      containers:
        - image: wasmcloud-secrets
          imagePullPolicy: IfNotPresent
          name: wasmcloud-secrets
          args:
            - "--backend-seed=$(BACKEND_SEED)"
            - "--nats-url=$(NATS_URL)"
          env:
            - name: BACKEND_SEED
              valueFrom:
                secretKeyRef:
                  name: wasmcloud-secrets
                  key: BACKEND_SEED
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: wasmcloud-secrets
                  key: NATS_URL
