apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../impersonation/

images:
  - name: wasmcloud-secrets
    newName: ghcr.io/wasmcloud/contrib/secrets-kubernetes
    newTag: dev

secretGenerator:
  - name: wasmcloud-secrets
    namespace: wasmcloud-secrets
    envs:
      - kubernetes-backend.env
